# Generated by Django 5.2.6 on 2025-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
