# Generated by Django 5.2.6 on 2025-12-19 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_useraddresses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddresses',
            new_name='UserAddress',
        ),
    ]
