# Generated by Django 5.2.6 on 2025-12-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
    ]
